language: node_js
node_js:
  - '9'
  - '8'
cache:
  directories:
    - ~/.npm

notifications:
  slack: parpe:ypxSy7CvUXYAShDK7C3supzV
  email: false

before_install:
  - npm install -g istanbul

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - rm -rf ./cc-test-reporter

after_success:
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/